# this is the standard controller that was set up for the RUM + CRAFTSMAN project
# removes the argument tags that were used in the original "oberon7_control/launch/joint_effort_controlllers.launch"
# in favor of static "rexrov" and "oberon7" parameters, so that this can be a separate launch file
rexrov:
  arm_position_controller:
    type: "position_controllers/JointGroupPositionController"
    joints:
      - oberon7/azimuth
      - oberon7/shoulder
      - oberon7/elbow
      - oberon7/roll
      - oberon7/pitch
      - oberon7/wrist
    oberon7:
      azimuth:
        pid: {p: 2000, i: 100, d: 50}
      shoulder:
        pid: {p: 2000, i: 100, d: 50}
      elbow:
        pid: {p: 2000, i: 100, d: 50}
      roll:
        pid: {p: 1000, i: 50, d: 10}
      pitch:
        pid: {p: 1000, i: 50, d: 10}
      wrist:
        pid: {p: 500, i: 30, d: 10}
